Setting:
  phase: train #train or test
  gpu_ids: [0] # [0,1,2,3, ... etc]

Path:
  Data_train:
  Data_test:

  resume_state:
  resume_model_dir:
  log_file_path:
  save_img:
  checkpoint_dir:

  pretrain_model_dir:
  pretrain_res:

Transforms:
  flip: True
  rot: True
  shuffle: True
  resize: 128

Model_Param:
  dataset_name:
  model_name:
  input_nc: 3
  output_nc: 3
  ngf:
  ndf:
  img_size: # should be same with 'Transforms'-'resize'
  init_type: normal  # network initialize type(normal/xavier/kaming/orthogonal)
  init_gain: 0.02 # std

Data_Param:
  batch_size: 1
  num_threads: 4

Train:
  n_epochs:
  beta1: 0.5
  beta2: 0.999
  lr:

Save:
  save_img_iter:
  print_iter:
