Setting:
  phase: train #train or test
  gpu_ids: [0] # [0,1,2,3, ... etc]

Path:
  Data_train: datasets/celeba-dataset/img_align_celeba

  resume_state: #results/sagan/resume/epoch_12.state
  resume_model_dir: results/sagan/resume
  log_file_path: results/sagan
  save_img: results/sagan/res_img
  checkpoint_dir: results/sagan/ckp

  pretrain_model_dir: results/pretrain/sagan
  pretrain_res: results/sagan/res_pretrain_img

Transforms:
  flip: False
  rot: False
  crop: False
  resize: 128 # should be power of 2 & more than 4 [4,16,32,64,128, etc]

Model_Param:
  dataset_name: celeba
  model_name: sagan
  model_type: resblock
  input_nc: 3
  output_nc: 3
  ngf: 64
  ndf: 64
  nz: 128
  img_size: 128 # should be same with 'Transforms'-'resize'
  init_type: normal # network initialize type
  init_gain: 0.02 # std
  loss_type: hinge # hinge/gan

Data_Param:
  batch_size: 15
  num_threads: 4

Train:
  n_epochs: 100
  iteration: 450000
  iteration_decay_start: 400000
  beta1: 0
  beta2: 0.9
  lr_g: 0.0001
  lr_d: 0.0004
  n_dis: 5 # resblock style: 5

Save:
  save_img_iter: 500
  print_iter: 100
