Setting:
  phase: train #train or test
  gpu_ids: [0] # [0,1,2,3, ... etc]

Path:
  Data_train: datasets/celeba-dataset/img_align_celeba

  resume_state: #results/wgan-gp/resume/epoch_12.state
  resume_model_dir: results/wgan-gp/resume
  log_file_path: results/wgan-gp
  save_img: results/wgan-gp/res_img
  checkpoint_dir: results/wgan-gp/ckp

  pretrain_model_dir: results/pretrain/wgan-gp
  pretrain_res: results/wgan-gp/res_pretrain_img

Transforms:
  flip: False
  rot: False
  crop: 178
  resize: 128 # should be power of 2 & more than 4 (4,16,32,64,128 etc)

Model_Param:
  dataset_name: celeba
  model_name: wgan-gp
  input_nc: 3
  output_nc: 3
  ngf: 64
  ndf: 64
  nz: 100
  img_size: 128 # should be same with 'Transforms'-'resize'
  init_type: normal # network initialize type
  init_gain: 0.02 # std

Data_Param:
  batch_size: 200
  num_threads: 4

Train:
  n_epochs: 50
  beta1: 0 # default 0
  beta2: 0.9 # default 0.9
  lr: 0.0001 # default 0.0001
  n_critic: 5
  lambda: 10 # gradient penalty coefficient default 10

Save:
  save_img_iter: 100
  print_iter: 100
